name: Generate ashteipa.json Workflow

on:
  workflow_dispatch:
  schedule:
    # هەموو ڕۆژێک بە شێوەیەکی ئۆتۆماتیکی سکرێپتەکە بەگەڕدەخات
    - cron: '0 0 * * *'

jobs:
  build-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Execute Build Script
        run: |
          python build_ashteipa.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ashteipa.json
          git commit -m "Update ashteipa.json with all games via build_ashteipa.py" || echo "No changes to commit"
          git push
