name: Auto Generate JSON Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # هەموو کاتژمێرێک جارێک کار دەکات

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python extractor.py

      - name: Commit and push generated JSON
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git stash
          git pull origin main --rebase || true
          git stash pop || true
          git add ashtemobile94.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update ashtemobile94.json" && git push)
